// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9g9ctAwAxrGuaDqaBlT61YENzd9aDCvs',
    appId: '1:1038455885933:web:d7167b327cef6adf37ef64',
    messagingSenderId: '1038455885933',
    projectId: 'smart-farming-66ff7',
    authDomain: 'smart-farming-66ff7.firebaseapp.com',
    storageBucket: 'smart-farming-66ff7.appspot.com',
    measurementId: 'G-06VBMQ8J7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDmWxrjExMbgU247swG7JmVd3XBGlwc4Q',
    appId: '1:1038455885933:android:6ac3a518447312b537ef64',
    messagingSenderId: '1038455885933',
    projectId: 'smart-farming-66ff7',
    storageBucket: 'smart-farming-66ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwB-yljAK0EQ6M5akEc-3ckM-M_zH-3o',
    appId: '1:1038455885933:ios:e8b41f0e9553aff337ef64',
    messagingSenderId: '1038455885933',
    projectId: 'smart-farming-66ff7',
    storageBucket: 'smart-farming-66ff7.appspot.com',
    androidClientId: '1038455885933-5mo35pl53jf8lrlte09iv7q4u9nknjjn.apps.googleusercontent.com',
    iosClientId: '1038455885933-4suhbjfe3kl3e9tqfo4n8gjk09tloae7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarming',
  );
}
